### PR TITLE
Big update select version is ok now :)

### PR DESCRIPTION
**Pull request by Angluca**
Very like it !!
--- 
Can be used normally after undo .
No matter how fast you press, It's all right :)
Come and try it ..

Check it out!

### CODE REVIEW

**Comment by Angluca** [comment]
Have bug.. Must fix them. T. T 5555

**Comment by Jorengarenar** [comment]
The snippet with _C include guards_ still doesn't work properly - placeholder gets skipped despite being marked as _noskip_.

I other snippets, default values don't work. I spam trigger, but it doesn't jump to the next one.

**Comment by Angluca** [comment]
Maybe you can comment example.
I'm a newbie haven't example test T. T

Have a question:
---
miniSnip have first write flag? like last flag <{+}> but It's first jump to
Maybe I didn't find?
```nim
# like this
<{+}>
<{3}>
<{1}> # I want first write 1 - 2 - 3, How to set flags?
<{2}>
```

**Comment by Angluca** [comment]
Well... Must more test . T. T

I just want snip good use on coding

**Comment by Jorengarenar** [comment]
Testing and proper **descriptions**!
If you feel uncomfortable writing in English language, I recommend tools like [Google Translate](https://translate.google.com), [DeepL](https://www.deepl.com/translator) or ChatGPT.

**Pull request closed without merging**
